### ISSUE TITLE
Issues with some types of keys

### ISSUE THREAD

**Issue by xiopt** [awuctl/licensing-stuff#4]
First of all, really nice collection of scripts. 
I was messing around with some old keys, and I seems the to_5x5 fails with Windows 7 and Office 2010 keys.

```
Traceback (most recent call last):
  File "/keycheck.py", line 255, in <module>
    response, message, success = query_key(pkey, PUB_LICENSE, pkc)
                                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/keycheck.py", line 148, in query_key
    pkey_data = ProductKeyDecoder(pkey)
  File "/licensing_stuff/keycutter.py", line 43, in __init__
    self.key = self.decode_5x5(key, self.ALPHABET)
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/licensing_stuff/keycutter.py", line 30, in decode_5x5
    dec = [key.index("N")]
           ~~~~~~~~~^^^^^
ValueError: substring not found

**Comment by xiopt** [comment]
I noticed now that this implements the msft:rm/algorithm/pkey/2009 algorithm and windows 7 and office 2010 keys are validated through the msft:rm/algorithm/pkey/2005 algorithm. I am curious how much differs the implementation and if it's possible to extract the group ID.
